[workspace]
members = [
	"zerobit",
	"zerobit-agent",
	"zerobit-chain",
	"zerobit-common",
	"zerobit-memory",
	"zerobit-model",
	"zerobit-prompt",
	"zerobit-tool",
	"zerobit-workflow",
]

[profile.dev]
split-debuginfo = "unpacked"
