[workspace]
members = [
	"versa",
	"versa-agent",
	"versa-chain",
	"versa-cli",
	"versa-common",
	"versa-memory",
	"versa-middleware",
	"versa-model",
	"versa-prompt",
	"versa-tool",
	"versa-workflow",
]

[profile.dev]
split-debuginfo = "unpacked"
