[package]
name = "versa-middleware"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
versa-common = { version = "0.1.0", path = "../versa-common" }
